(define (problem pass-the-ball-simple)
   (:domain pass-the-ball)
   (:objects allison nomar noah ramon julia raj oliver naomi irina jason angelo rosario a n r j o i h room1 room2)
   (:init (has-first-letter allison a)
          (has-first-letter nomar n)
          (has-first-letter noah n)
          (has-first-letter ramon r)
          (has-first-letter julia j)
          (has-first-letter raj r)
          (has-first-letter oliver o)
          (has-first-letter naomi n)
          (has-first-letter irina i)
          (has-first-letter jason j)
          (has-first-letter angelo a)
          (has-first-letter rosario r)
          
          (has-last-letter allison n)
          (has-last-letter nomar r)
          (has-last-letter ramon n)
          (has-last-letter julia a)
          (has-last-letter raj j)
          (has-last-letter oliver r)
          (has-last-letter naomi i)
          (has-last-letter irina a)
          (has-last-letter jason n)
          (has-last-letter angelo o)
          (has-last-letter rosario o)
          (has-last-letter noah h)
          
          (in-room allison room1)
          (in-room nomar room1)
          (in-room noah room1)
          (in-room ramon room1)
          (in-room julia room1)
          (in-room raj room1)
          (in-room oliver room2)
          (in-room naomi room2) 
          (in-room irina room2)
          (in-room jason room2)
          (in-room angelo room2)
          (in-room rosario room2)

          (is-room room1)
          (is-room room2)
          
          (has-ball allison))
   (:goal (has-ball rosario)))
   
   
   